source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HPUIViewExtensions_Example', :exclusive => true do
  pod "HPUIViewExtensions", :path => "../"
end

target 'HPUIViewExtensions_Tests', :exclusive => true do
  pod "HPUIViewExtensions", :path => "../"

  
end
